### ISSUE TITLE
support release-drafter?

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/.github#11]
[release-drafter](https://github.com/release-drafter/release-drafter) is widely used on GitHub. e.g. @jenkinsci use it in all repos release.  here is the config in [jenkinsci/.github](https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.yml).

release-drafter can help us draft release notes and sort changelog. For example https://github.com/jenkinsci/docker/releases/tag/2.440

and it can be created in .github repo and used by other repos in cpp-linter org. (I don't want to use [GitHub release.yml](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configurations) because it does not support this feature, see the discussion https://github.com/orgs/community/discussions/7926)

**Comment by 2bndy5** [comment]
Sure. Seems nice. In the past, I've used gh-cli directly in in a CI workflow to create a release when a tag (starting with `v*`) is pushed.

```yml
      - name: Create a Github Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} --generate-notes
``` 
But that action seems much more suited for customizing the generated list of changes.
