### ISSUE TITLE
stale bot is now deprecated

### ISSUE THREAD

**Issue by 2bndy5** [cpp-linter/.github#22]
According to bot support page:
> 📯 The stale app is deprecated and this repository is no longer maintained
> 
> Please use [the stale action](https://github.com/actions/stale) instead.

Also, according to the [bot's source code repo](https://github.com/probot/stale):
> This repository has been archived by the owner on May 19, 2023. It is now read-only.

----
This calls for another reusable workflow. Here's a [actions/stale](https://github.com/actions/stale) example that I think would work for our needs:
```yml
name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'
permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: >-
            This issue has been automatically marked as stale because
            it has not had recent activity.
            It will be closed if no further activity occurs. 
          # Better to exclude certain issues from being marked as stale
          exempt-issue-labels: 'help wanted'
```
